### ISSUE TITLE
Explain how to point to stand-alone Sia node

### ISSUE THREAD

**Issue by m-cat** [SkynetLabs/skynet-webportal#1437]
## Overview

I didn't see this in the docs and it's very helpful. However the actual method of doing this is (for me) a total black box.

## Design or Proposal

From @ro-tex on Discord:

What you want to do is create a file called docker-compose.override.yml in the main project dir and have this in it:
```
version: "3.7"

services:
  sia:
    profiles:
      - donotstart
```

you can actually override anything you want, so mine starts like this:

```
version: "3.7"

services:

  sia:
    build:
      args:
        branch: master
    volumes:
      - /Users/inovakov/sia_data:/sia-data
    profiles:
      - donotstart
```

This allows me to point the sia service to the same directory where my stand-alone sia node is keeping its data. I just make sure I'm only running one of them at a time.
