### ISSUE TITLE
improve certbot configuration and documentation

### ISSUE THREAD

**Issue by kwypchlo** [SkynetLabs/skynet-webportal#1912]
It should be easier for portal operators to use different certbot dns plugin ie. cloudflare.

List of all dns plugins: https://hub.docker.com/r/certbot/certbot

```yaml
certbot:
  image: certbot/dns-route53:v1.25.0
  entrypoint: sh /entrypoint.sh
  container_name: certbot
  restart: unless-stopped
  logging: *default-logging
  env_file:
    - .env
  environment:
    - CERTBOT_ARGS=--dns-route53
  volumes:
    - ./docker/certbot/entrypoint.sh:/entrypoint.sh
    - ./docker/data/certbot:/etc/letsencrypt
```

Right now, to replace [dns-route53](https://hub.docker.com/r/certbot/dns-route53) plugin with [dns-cloudflare](https://hub.docker.com/r/certbot/dns-cloudflare) portal operator needs to make sure cloudflare api key is available in the env file and add this to docker-compose.override.yml manually:

```yaml
certbot:
  image: certbot/dns-cloudflare:v1.25.0
  environment:
    - CERTBOT_ARGS=--dns-cloudflare
```

We would like to be able to use a config to select the plugin and let ansible generate proper override file entry.
